<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>b0599b06-d681-4216-b999-a66e3c85a922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.px-4.w-100.text-uppercase.btn.btn-dark-green</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-page']/div/div/div/div/form/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71d4fd3f-902c-4e6f-ba65-4c333f5d0012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 w-100 text-uppercase btn btn-dark-green</value>
      <webElementGuid>21f8a630-94fd-44ec-bc8b-b4f16f36251f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>0843b4bc-c6e8-445c-8468-3e4c4ef0a173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-page&quot;)/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-12 col-sm-8 col-lg-4&quot;]/div[@class=&quot;p-4 card&quot;]/div[@class=&quot;p-0 card-body&quot;]/form[1]/button[@class=&quot;px-4 w-100 text-uppercase btn btn-dark-green&quot;]</value>
      <webElementGuid>e1724e56-72d9-43f9-b17c-a1a9f4287e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-page']/div/div/div/div/form/button</value>
      <webElementGuid>318bdbc6-93d3-4eda-9967-c445c6ea46e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login dengan SSO'])[1]/preceding::button[1]</value>
      <webElementGuid>b23ac30f-aedf-4726-a796-78aa9e5b8304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>d283a3b1-3d99-4657-ba1a-99e987287d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>07650691-b1c1-4458-b0d5-0e1bd3d56e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>679475f1-9ef4-40d7-8671-defddac0786f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
