<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_510152550100</name>
   <tag></tag>
   <elementGuidId>3a18e8af-64bf-4f5a-964a-fb2eb2ac4e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showingData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='showingData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>797a5a22-88a1-4b6b-a0fb-3ee160c80270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>showingData</value>
      <webElementGuid>9f5f1338-e7c9-459a-b31e-2ddd1df29e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showingData</value>
      <webElementGuid>ab46a6ee-3d2a-456b-8331-cd7b61c2ffc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectShowingItem form-control</value>
      <webElementGuid>193089a8-2c0e-4382-8b66-efe9b9707a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>510152550100</value>
      <webElementGuid>9448651d-4957-4f32-ad32-e78447fb6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showingData&quot;)</value>
      <webElementGuid>f394f162-9b9e-499b-8705-d127b92c700e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='showingData']</value>
      <webElementGuid>0836df39-341c-4893-bce0-5fce98205ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div[2]/div/div/div/div[3]/div/div[2]/select</value>
      <webElementGuid>b454afc4-60e0-429e-834d-ba200c97ef64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada'])[10]/following::select[1]</value>
      <webElementGuid>36b35065-916f-4378-93aa-2b9e8d577dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada role'])[1]/following::select[1]</value>
      <webElementGuid>84d74b86-44eb-46a2-8d8b-da906c4ac542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f10fe80d-b0be-4b95-b616-65280af01afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'showingData' and @id = 'showingData' and (text() = '510152550100' or . = '510152550100')]</value>
      <webElementGuid>6693a76a-168d-4f27-983b-a3ddcb3b9f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'showingData', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>e36cb7ee-7820-45a1-9c10-314f8d710ae1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
