<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Nama</name>
   <tag></tag>
   <elementGuidId>5902a52b-ae16-47d5-badf-7cf7d43a8c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th[title=&quot;Nama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/main/div[2]/div/div/div/div[2]/div/div/table/thead/tr/th[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>894e52d5-feb1-425a-a97f-4b0da6760cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-only-head</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef8b3d2d-f5d0-4be7-a4b2-b6b50660ff3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>600e9d25-2148-4b03-b6fe-cb4d4d5853d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>9541b500-6b63-495b-93b0-79b2186df82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>e972f211-6486-4fcf-b3e5-2ff9866fca11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;react-bs-table-container&quot;]/div[@class=&quot;react-bs-table react-bs-table-bordered&quot;]/div[@class=&quot;react-bs-container-header table-header-wrapper&quot;]/table[@class=&quot;table table-hover table-bordered&quot;]/thead[1]/tr[1]/th[3]</value>
      <webElementGuid>5595fbca-35c8-4891-a7bb-0a97b0d1bf87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div[2]/div/div/div/div[2]/div/div/table/thead/tr/th[3]</value>
      <webElementGuid>7be1e2b2-eae8-48e3-9105-1f7550b8df9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIP'])[1]/following::th[1]</value>
      <webElementGuid>dda88e90-da28-46a6-8aa9-8feb8554c8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::th[2]</value>
      <webElementGuid>ab783a92-d138-4b4e-bf42-5bf41a14a3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi'])[1]/preceding::th[1]</value>
      <webElementGuid>3ae2ee16-9eeb-4af0-a7c4-71e56578918e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/preceding::th[2]</value>
      <webElementGuid>dfdd4c3d-9549-4b2c-956a-33f3ddd2ef9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama']/parent::*</value>
      <webElementGuid>951cc05d-3172-4dac-ac0f-13f3d0f1e386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]</value>
      <webElementGuid>f501dcdd-1c9a-45c9-807e-92bea6565470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@title = 'Nama' and (text() = 'Nama' or . = 'Nama')]</value>
      <webElementGuid>9633fa4f-2a70-42f1-b443-8b7b267b0592</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
