<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cetak Laporan</name>
   <tag></tag>
   <elementGuidId>606ec2ed-5b3d-451a-a5e7-8c4727405987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pl-0.col-auto > button.buttonSimpan.mb-4.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa81e539-7fc8-45d6-a3ba-2f7276eb38d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cbc9e6d-4951-4f8c-81cb-b2defa8cde1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonSimpan mb-4 btn btn-secondary</value>
      <webElementGuid>7c15f217-f5e8-4bc5-a8da-e32674227647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cetak Laporan </value>
      <webElementGuid>5a671b13-3348-4cf6-a301-0b3aa9f61971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pl-0 col-auto&quot;]/button[@class=&quot;buttonSimpan mb-4 btn btn-secondary&quot;]</value>
      <webElementGuid>519bac7c-7bbb-4731-ade3-eaf65a668574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>2a0888c1-2564-4743-a2de-a0d91b125ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div[2]/div/div[3]/div/div[2]/div[3]/button</value>
      <webElementGuid>2fc2828c-fdb9-4f57-9929-c48a3702023b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Rekap'])[1]/following::button[1]</value>
      <webElementGuid>1eb1f6c2-a49f-4497-bc7e-8efc06162094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::button[2]</value>
      <webElementGuid>752c0e46-aeff-46c9-9f61-63c031a5cd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::button[1]</value>
      <webElementGuid>c15cdbb9-8c99-4078-811c-0bc2180f50f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TanggalStatus'])[1]/preceding::button[1]</value>
      <webElementGuid>f3f49244-a398-4895-a3cf-832ecf59e239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>e23a0e5e-0920-47b2-914b-5f5afe9f813c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cetak Laporan ' or . = 'Cetak Laporan ')]</value>
      <webElementGuid>8e68af92-93c9-42c6-8194-b137635b489d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
