<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_510152550100</name>
   <tag></tag>
   <elementGuidId>963218a4-4425-413f-8904-020f260fb54e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showingData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='showingData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>71eef21d-01ed-42c5-a386-e6a6b54934a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>showingData</value>
      <webElementGuid>5f1b5617-3f9e-4efa-a027-f893f2f4e0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showingData</value>
      <webElementGuid>b5bcb3bd-819d-4429-92f3-0ca117ef0831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectShowingItem form-control</value>
      <webElementGuid>ef9db64a-b0ed-47dd-839e-986a4fb24115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>510152550100</value>
      <webElementGuid>40314023-18f3-4b7f-9268-c673eee2429c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showingData&quot;)</value>
      <webElementGuid>a5adb589-b34c-4a26-a86f-9ae2f304a973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='showingData']</value>
      <webElementGuid>dcb95aed-8dee-4ee0-b818-4ac132005fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div[2]/div/div[3]/div/div[4]/div/div[2]/select</value>
      <webElementGuid>e6b243a6-ff29-4422-82c1-8d0dcb824fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[10]/following::select[1]</value>
      <webElementGuid>fb818e2f-bd2b-44a3-b471-c846fa445e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[10]/following::select[1]</value>
      <webElementGuid>ef1fc202-7052-48d8-9702-11f2623ba0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='…'])[1]/preceding::select[1]</value>
      <webElementGuid>48f64700-d950-43d2-8499-2a22dfddc10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'showingData', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>28c7838e-1066-432a-a911-fa4ddb2404ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ba08dfdd-21a9-4676-ac69-220250fc46e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'showingData' and @id = 'showingData' and (text() = '510152550100' or . = '510152550100')]</value>
      <webElementGuid>568c11b3-f488-4f8c-8f0c-15736b1ec2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
