<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Photo</name>
   <tag></tag>
   <elementGuidId>d178b409-a269-4b54-bc12-aeaeebfe4b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>table.table.table-hover.table-bordered > thead > tr > th:nth-of-type(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/main/div[2]/div/div[3]/div/div[3]/div/div/table/thead/tr/th[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>da7699d5-6391-494b-83a6-3a9e794aebc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-only-head</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66b71baf-e00e-4815-bd0d-986d21d5496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>fileNames</value>
      <webElementGuid>92da8225-f3cd-4e93-9200-44aee3bc5d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Photo</value>
      <webElementGuid>4539d124-0ca8-486c-bc3c-1aecf9288149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;react-bs-table-container&quot;]/div[@class=&quot;react-bs-table react-bs-table-bordered&quot;]/div[@class=&quot;react-bs-container-header table-header-wrapper&quot;]/table[@class=&quot;table table-hover table-bordered&quot;]/thead[1]/tr[1]/th[4]</value>
      <webElementGuid>3322669d-1273-4a0d-aca9-443d458a786a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/main/div[2]/div/div[3]/div/div[3]/div/div/table/thead/tr/th[4]</value>
      <webElementGuid>371af793-28c5-43ac-af5c-6a7e3cd870b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TanggalKontrak'])[1]/following::th[1]</value>
      <webElementGuid>16ab8dc5-1ae1-4a82-ae32-524aefc25dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TanggalStatus'])[1]/following::th[2]</value>
      <webElementGuid>04268b4d-9e8b-49bc-94a1-3511aa14f874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NoKredit'])[1]/preceding::th[1]</value>
      <webElementGuid>ee0d6a65-3173-4f13-b46b-8fa790340e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/preceding::th[2]</value>
      <webElementGuid>5ca53d9e-f41f-40da-9f69-a10eed020bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Photo']/parent::*</value>
      <webElementGuid>af150f38-83b3-435a-bac6-dfe86693ab9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/table/thead/tr/th[4]</value>
      <webElementGuid>692d575c-48b3-4024-9948-a3f1775945bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Photo' or . = 'Photo')]</value>
      <webElementGuid>930f0f05-1d4e-4520-acdd-d2f7f30b04c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
